---

- name: Install required dependencies
  apt:
    name:
      - unzip
      - curl
    state: present
    update_cache: yes

- name: Download Jenkins GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins APT repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins

- name: Installing Java and Jenkins
  ansible.builtin.apt:
    name:
      - openjdk-11-jdk
      - openjdk-17-jdk      
      - jenkins
    state: present
    update_cache: yes

- name: Start Jenkins service
  ansible.builtin.systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Add Jenkins user to Docker group
  ansible.builtin.user:
    name: jenkins
    group: docker
    append: yes

- name: Install Maven (for Java builds)
  apt:
    name: maven
    state: present

- name: Download AWS CLI v2 bundle
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"
    mode: '0644'

- name: Unzip AWS CLI bundle
  unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: yes

- name: Run AWS CLI install script
  command: "/tmp/aws/install"
  args:
    creates: "/usr/local/bin/aws"

- name: Verify AWS CLI installation
  command: "aws --version"
  register: aws_cli_version

- name: Print AWS CLI version
  debug:
    msg: "Installed AWS CLI version: {{ aws_cli_version.stdout }}"


- name: Restart Docker to apply group changes
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart Jenkins to refresh group membership
  ansible.builtin.systemd:
    name: jenkins
    state: restarted
