---

- name: Create Docker volume for Postgress
  docker_volume:
    name: sonar_db_data
  

- name: Postgress container for SonarQube
  docker_container:
    name: sonar_db
    image: postgres:13
    restart_policy: unless-stopped
    env:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonar_db_data:/var/lib/postgresql/data

- name: Create Docker volume for SonarQube
  docker_volume:
    name: sonarqube_data

- name: Create Docker volume for SonarQube extensions
  docker_volume:
    name: sonarqube_extensions

- name: Run SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube:lts
    restart_policy: unless-stopped
    published_ports:
      - "9000:9000"
    env:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    links:
      - sonar_db